// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anim_proto.proto

#include "anim_proto.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR anim_proto_mssg::anim_proto_mssg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.clips_)*/{}
  , /*decltype(_impl_.numclips_)*/0u
  , /*decltype(_impl_.skelsize_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct anim_proto_mssgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR anim_proto_mssgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~anim_proto_mssgDefaultTypeInternal() {}
  union {
    anim_proto_mssg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 anim_proto_mssgDefaultTypeInternal _anim_proto_mssg_default_instance_;

// ===================================================================

class anim_proto_mssg::_Internal {
 public:
};

void anim_proto_mssg::clear_clips() {
  _impl_.clips_.Clear();
}
anim_proto_mssg::anim_proto_mssg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:anim_proto_mssg)
}
anim_proto_mssg::anim_proto_mssg(const anim_proto_mssg& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  anim_proto_mssg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.clips_){from._impl_.clips_}
    , decltype(_impl_.numclips_){}
    , decltype(_impl_.skelsize_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&_impl_.numclips_, &from._impl_.numclips_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.skelsize_) -
    reinterpret_cast<char*>(&_impl_.numclips_)) + sizeof(_impl_.skelsize_));
  // @@protoc_insertion_point(copy_constructor:anim_proto_mssg)
}

inline void anim_proto_mssg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.clips_){arena}
    , decltype(_impl_.numclips_){0u}
    , decltype(_impl_.skelsize_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

anim_proto_mssg::~anim_proto_mssg() {
  // @@protoc_insertion_point(destructor:anim_proto_mssg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void anim_proto_mssg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.clips_.~RepeatedPtrField();
}

void anim_proto_mssg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void anim_proto_mssg::Clear() {
// @@protoc_insertion_point(message_clear_start:anim_proto_mssg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clips_.Clear();
  ::memset(&_impl_.numclips_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.skelsize_) -
      reinterpret_cast<char*>(&_impl_.numclips_)) + sizeof(_impl_.skelsize_));
  _internal_metadata_.Clear<std::string>();
}

const char* anim_proto_mssg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 numclips = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.numclips_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 skelsize = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.skelsize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .clip_proto_mssg clips = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_clips(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* anim_proto_mssg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:anim_proto_mssg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 numclips = 1;
  if (this->_internal_numclips() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_numclips(), target);
  }

  // uint32 skelsize = 2;
  if (this->_internal_skelsize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_skelsize(), target);
  }

  // repeated .clip_proto_mssg clips = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_clips_size()); i < n; i++) {
    const auto& repfield = this->_internal_clips(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:anim_proto_mssg)
  return target;
}

size_t anim_proto_mssg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:anim_proto_mssg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .clip_proto_mssg clips = 3;
  total_size += 1UL * this->_internal_clips_size();
  for (const auto& msg : this->_impl_.clips_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 numclips = 1;
  if (this->_internal_numclips() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_numclips());
  }

  // uint32 skelsize = 2;
  if (this->_internal_skelsize() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_skelsize());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void anim_proto_mssg::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const anim_proto_mssg*>(
      &from));
}

void anim_proto_mssg::MergeFrom(const anim_proto_mssg& from) {
  anim_proto_mssg* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:anim_proto_mssg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.clips_.MergeFrom(from._impl_.clips_);
  if (from._internal_numclips() != 0) {
    _this->_internal_set_numclips(from._internal_numclips());
  }
  if (from._internal_skelsize() != 0) {
    _this->_internal_set_skelsize(from._internal_skelsize());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void anim_proto_mssg::CopyFrom(const anim_proto_mssg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:anim_proto_mssg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool anim_proto_mssg::IsInitialized() const {
  return true;
}

void anim_proto_mssg::InternalSwap(anim_proto_mssg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.clips_.InternalSwap(&other->_impl_.clips_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(anim_proto_mssg, _impl_.skelsize_)
      + sizeof(anim_proto_mssg::_impl_.skelsize_)
      - PROTOBUF_FIELD_OFFSET(anim_proto_mssg, _impl_.numclips_)>(
          reinterpret_cast<char*>(&_impl_.numclips_),
          reinterpret_cast<char*>(&other->_impl_.numclips_));
}

std::string anim_proto_mssg::GetTypeName() const {
  return "anim_proto_mssg";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::anim_proto_mssg*
Arena::CreateMaybeMessage< ::anim_proto_mssg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::anim_proto_mssg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
