// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bone_proto.proto

#include "bone_proto.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR bone_proto_mssg::bone_proto_mssg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.scale_)*/nullptr
  , /*decltype(_impl_.trans_)*/nullptr
  , /*decltype(_impl_.rot_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct bone_proto_mssgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR bone_proto_mssgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~bone_proto_mssgDefaultTypeInternal() {}
  union {
    bone_proto_mssg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 bone_proto_mssgDefaultTypeInternal _bone_proto_mssg_default_instance_;

// ===================================================================

class bone_proto_mssg::_Internal {
 public:
  static const ::vec3_proto_mssg& scale(const bone_proto_mssg* msg);
  static const ::vec3_proto_mssg& trans(const bone_proto_mssg* msg);
  static const ::vec4_proto_mssg& rot(const bone_proto_mssg* msg);
};

const ::vec3_proto_mssg&
bone_proto_mssg::_Internal::scale(const bone_proto_mssg* msg) {
  return *msg->_impl_.scale_;
}
const ::vec3_proto_mssg&
bone_proto_mssg::_Internal::trans(const bone_proto_mssg* msg) {
  return *msg->_impl_.trans_;
}
const ::vec4_proto_mssg&
bone_proto_mssg::_Internal::rot(const bone_proto_mssg* msg) {
  return *msg->_impl_.rot_;
}
void bone_proto_mssg::clear_scale() {
  if (GetArenaForAllocation() == nullptr && _impl_.scale_ != nullptr) {
    delete _impl_.scale_;
  }
  _impl_.scale_ = nullptr;
}
void bone_proto_mssg::clear_trans() {
  if (GetArenaForAllocation() == nullptr && _impl_.trans_ != nullptr) {
    delete _impl_.trans_;
  }
  _impl_.trans_ = nullptr;
}
void bone_proto_mssg::clear_rot() {
  if (GetArenaForAllocation() == nullptr && _impl_.rot_ != nullptr) {
    delete _impl_.rot_;
  }
  _impl_.rot_ = nullptr;
}
bone_proto_mssg::bone_proto_mssg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:bone_proto_mssg)
}
bone_proto_mssg::bone_proto_mssg(const bone_proto_mssg& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  bone_proto_mssg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.scale_){nullptr}
    , decltype(_impl_.trans_){nullptr}
    , decltype(_impl_.rot_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_scale()) {
    _this->_impl_.scale_ = new ::vec3_proto_mssg(*from._impl_.scale_);
  }
  if (from._internal_has_trans()) {
    _this->_impl_.trans_ = new ::vec3_proto_mssg(*from._impl_.trans_);
  }
  if (from._internal_has_rot()) {
    _this->_impl_.rot_ = new ::vec4_proto_mssg(*from._impl_.rot_);
  }
  // @@protoc_insertion_point(copy_constructor:bone_proto_mssg)
}

inline void bone_proto_mssg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.scale_){nullptr}
    , decltype(_impl_.trans_){nullptr}
    , decltype(_impl_.rot_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

bone_proto_mssg::~bone_proto_mssg() {
  // @@protoc_insertion_point(destructor:bone_proto_mssg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void bone_proto_mssg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.scale_;
  if (this != internal_default_instance()) delete _impl_.trans_;
  if (this != internal_default_instance()) delete _impl_.rot_;
}

void bone_proto_mssg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void bone_proto_mssg::Clear() {
// @@protoc_insertion_point(message_clear_start:bone_proto_mssg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.scale_ != nullptr) {
    delete _impl_.scale_;
  }
  _impl_.scale_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.trans_ != nullptr) {
    delete _impl_.trans_;
  }
  _impl_.trans_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.rot_ != nullptr) {
    delete _impl_.rot_;
  }
  _impl_.rot_ = nullptr;
  _internal_metadata_.Clear<std::string>();
}

const char* bone_proto_mssg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .vec3_proto_mssg scale = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_scale(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .vec3_proto_mssg trans = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_trans(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .vec4_proto_mssg rot = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_rot(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* bone_proto_mssg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bone_proto_mssg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .vec3_proto_mssg scale = 1;
  if (this->_internal_has_scale()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::scale(this),
        _Internal::scale(this).GetCachedSize(), target, stream);
  }

  // .vec3_proto_mssg trans = 2;
  if (this->_internal_has_trans()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::trans(this),
        _Internal::trans(this).GetCachedSize(), target, stream);
  }

  // .vec4_proto_mssg rot = 3;
  if (this->_internal_has_rot()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::rot(this),
        _Internal::rot(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bone_proto_mssg)
  return target;
}

size_t bone_proto_mssg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bone_proto_mssg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .vec3_proto_mssg scale = 1;
  if (this->_internal_has_scale()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.scale_);
  }

  // .vec3_proto_mssg trans = 2;
  if (this->_internal_has_trans()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.trans_);
  }

  // .vec4_proto_mssg rot = 3;
  if (this->_internal_has_rot()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.rot_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void bone_proto_mssg::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const bone_proto_mssg*>(
      &from));
}

void bone_proto_mssg::MergeFrom(const bone_proto_mssg& from) {
  bone_proto_mssg* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:bone_proto_mssg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_scale()) {
    _this->_internal_mutable_scale()->::vec3_proto_mssg::MergeFrom(
        from._internal_scale());
  }
  if (from._internal_has_trans()) {
    _this->_internal_mutable_trans()->::vec3_proto_mssg::MergeFrom(
        from._internal_trans());
  }
  if (from._internal_has_rot()) {
    _this->_internal_mutable_rot()->::vec4_proto_mssg::MergeFrom(
        from._internal_rot());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void bone_proto_mssg::CopyFrom(const bone_proto_mssg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bone_proto_mssg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool bone_proto_mssg::IsInitialized() const {
  return true;
}

void bone_proto_mssg::InternalSwap(bone_proto_mssg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(bone_proto_mssg, _impl_.rot_)
      + sizeof(bone_proto_mssg::_impl_.rot_)
      - PROTOBUF_FIELD_OFFSET(bone_proto_mssg, _impl_.scale_)>(
          reinterpret_cast<char*>(&_impl_.scale_),
          reinterpret_cast<char*>(&other->_impl_.scale_));
}

std::string bone_proto_mssg::GetTypeName() const {
  return "bone_proto_mssg";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bone_proto_mssg*
Arena::CreateMaybeMessage< ::bone_proto_mssg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bone_proto_mssg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
