// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_proto.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_key_5fproto_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_key_5fproto_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_key_5fproto_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_key_5fproto_2eproto {
  static const uint32_t offsets[];
};
class key_proto_mssg;
struct key_proto_mssgDefaultTypeInternal;
extern key_proto_mssgDefaultTypeInternal _key_proto_mssg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::key_proto_mssg* Arena::CreateMaybeMessage<::key_proto_mssg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class key_proto_mssg final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:key_proto_mssg) */ {
 public:
  inline key_proto_mssg() : key_proto_mssg(nullptr) {}
  ~key_proto_mssg() override;
  explicit PROTOBUF_CONSTEXPR key_proto_mssg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  key_proto_mssg(const key_proto_mssg& from);
  key_proto_mssg(key_proto_mssg&& from) noexcept
    : key_proto_mssg() {
    *this = ::std::move(from);
  }

  inline key_proto_mssg& operator=(const key_proto_mssg& from) {
    CopyFrom(from);
    return *this;
  }
  inline key_proto_mssg& operator=(key_proto_mssg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const key_proto_mssg& default_instance() {
    return *internal_default_instance();
  }
  static inline const key_proto_mssg* internal_default_instance() {
    return reinterpret_cast<const key_proto_mssg*>(
               &_key_proto_mssg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(key_proto_mssg& a, key_proto_mssg& b) {
    a.Swap(&b);
  }
  inline void Swap(key_proto_mssg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(key_proto_mssg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  key_proto_mssg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<key_proto_mssg>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const key_proto_mssg& from);
  void MergeFrom(const key_proto_mssg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(key_proto_mssg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "key_proto_mssg";
  }
  protected:
  explicit key_proto_mssg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kWFieldNumber = 4,
    kHFieldNumber = 5,
  };
  // uint32 key = 1;
  void clear_key();
  uint32_t key() const;
  void set_key(uint32_t value);
  private:
  uint32_t _internal_key() const;
  void _internal_set_key(uint32_t value);
  public:

  // uint32 x = 2;
  void clear_x();
  uint32_t x() const;
  void set_x(uint32_t value);
  private:
  uint32_t _internal_x() const;
  void _internal_set_x(uint32_t value);
  public:

  // uint32 y = 3;
  void clear_y();
  uint32_t y() const;
  void set_y(uint32_t value);
  private:
  uint32_t _internal_y() const;
  void _internal_set_y(uint32_t value);
  public:

  // uint32 w = 4;
  void clear_w();
  uint32_t w() const;
  void set_w(uint32_t value);
  private:
  uint32_t _internal_w() const;
  void _internal_set_w(uint32_t value);
  public:

  // uint32 h = 5;
  void clear_h();
  uint32_t h() const;
  void set_h(uint32_t value);
  private:
  uint32_t _internal_h() const;
  void _internal_set_h(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:key_proto_mssg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t key_;
    uint32_t x_;
    uint32_t y_;
    uint32_t w_;
    uint32_t h_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_key_5fproto_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// key_proto_mssg

// uint32 key = 1;
inline void key_proto_mssg::clear_key() {
  _impl_.key_ = 0u;
}
inline uint32_t key_proto_mssg::_internal_key() const {
  return _impl_.key_;
}
inline uint32_t key_proto_mssg::key() const {
  // @@protoc_insertion_point(field_get:key_proto_mssg.key)
  return _internal_key();
}
inline void key_proto_mssg::_internal_set_key(uint32_t value) {
  
  _impl_.key_ = value;
}
inline void key_proto_mssg::set_key(uint32_t value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:key_proto_mssg.key)
}

// uint32 x = 2;
inline void key_proto_mssg::clear_x() {
  _impl_.x_ = 0u;
}
inline uint32_t key_proto_mssg::_internal_x() const {
  return _impl_.x_;
}
inline uint32_t key_proto_mssg::x() const {
  // @@protoc_insertion_point(field_get:key_proto_mssg.x)
  return _internal_x();
}
inline void key_proto_mssg::_internal_set_x(uint32_t value) {
  
  _impl_.x_ = value;
}
inline void key_proto_mssg::set_x(uint32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:key_proto_mssg.x)
}

// uint32 y = 3;
inline void key_proto_mssg::clear_y() {
  _impl_.y_ = 0u;
}
inline uint32_t key_proto_mssg::_internal_y() const {
  return _impl_.y_;
}
inline uint32_t key_proto_mssg::y() const {
  // @@protoc_insertion_point(field_get:key_proto_mssg.y)
  return _internal_y();
}
inline void key_proto_mssg::_internal_set_y(uint32_t value) {
  
  _impl_.y_ = value;
}
inline void key_proto_mssg::set_y(uint32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:key_proto_mssg.y)
}

// uint32 w = 4;
inline void key_proto_mssg::clear_w() {
  _impl_.w_ = 0u;
}
inline uint32_t key_proto_mssg::_internal_w() const {
  return _impl_.w_;
}
inline uint32_t key_proto_mssg::w() const {
  // @@protoc_insertion_point(field_get:key_proto_mssg.w)
  return _internal_w();
}
inline void key_proto_mssg::_internal_set_w(uint32_t value) {
  
  _impl_.w_ = value;
}
inline void key_proto_mssg::set_w(uint32_t value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:key_proto_mssg.w)
}

// uint32 h = 5;
inline void key_proto_mssg::clear_h() {
  _impl_.h_ = 0u;
}
inline uint32_t key_proto_mssg::_internal_h() const {
  return _impl_.h_;
}
inline uint32_t key_proto_mssg::h() const {
  // @@protoc_insertion_point(field_get:key_proto_mssg.h)
  return _internal_h();
}
inline void key_proto_mssg::_internal_set_h(uint32_t value) {
  
  _impl_.h_ = value;
}
inline void key_proto_mssg::set_h(uint32_t value) {
  _internal_set_h(value);
  // @@protoc_insertion_point(field_set:key_proto_mssg.h)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_key_5fproto_2eproto
